// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EdgeFormEditor.Models;

public partial class Autofill
{
    public string Name { get; set; }

    public string Value { get; set; }

    public string ValueLower { get; set; }

    public int? DateCreated { get; set; }

    public int? DateLastUsed { get; set; }

    public int? Count { get; set; }
}