// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EdgeFormEditor.Models;

public partial class WebDataDbContext : DbContext
{
    public WebDataDbContext(DbContextOptions<WebDataDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Autofill> Autofills { get; set; }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Autofill>(entity =>
        {
            entity.HasKey(e => new { e.Name, e.Value });

            entity.ToTable("autofill");

            entity.HasIndex(e => e.Name, "autofill_name");

            entity.HasIndex(e => new { e.Name, e.ValueLower }, "autofill_name_value_lower");

            entity.Property(e => e.Name)
                .HasColumnType("VARCHAR")
                .HasColumnName("name");
            entity.Property(e => e.Value)
                .HasColumnType("VARCHAR")
                .HasColumnName("value");
            entity.Property(e => e.Count)
                .HasDefaultValue(1)
                .HasColumnName("count");
            entity.Property(e => e.DateCreated)
                .HasDefaultValue(0)
                .HasColumnName("date_created");
            entity.Property(e => e.DateLastUsed)
                .HasDefaultValue(0)
                .HasColumnName("date_last_used");
            entity.Property(e => e.ValueLower)
                .HasColumnType("VARCHAR")
                .HasColumnName("value_lower");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}